version: '3'

services:
    # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '82:80'
      - '443:443'
    restart: always
    volumes: 
        - wordpress_data:/var/www/html/
        - ./src/theme/:/var/www/html/wp-content/themes
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: gritauser
      WORDPRESS_DB_PASSWORD: 06199700ZoiR
    networks:
      - wpsite
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 06199700ZoiR
      MYSQL_DATABASE: dbnaogrita    
      MYSQL_USER: gritauser
      MYSQL_PASSWORD: 06199700ZoiR
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '88:80'
    environment:
      PMA_HOST: db:3306
      MYSQL_ROOT_PASSWORD: 06199700ZoiR 
    networks:
      - wpsite
  
networks:
  wpsite:
volumes:
  db_data: {}
  wordpress_data: {}